export const columnStorageKey = 'project.manage.visible-columns.v5'
export const actionColumnWidth = '56px'

export const defaultVisibleColumns = {
  client: true,
  projectType: true,
  project: true,
  inquirySource: false,
  value: true,
  update: true,
  owner: true,
  vendor: false,
  vendorContactName: false,
  vendorMobile: false,
  vendorEmail: false,
  award: true,
  status: true,
}

export const requiredColumns = new Set(['client', 'project', 'status'])

export const dataColumns = [
  { key: 'client', label: 'Client', width: '220px', sortable: true, sortType: 'string' },
  { key: 'projectType', label: 'Project Type', width: '160px', sortable: true, sortType: 'string' },
  {
    key: 'project',
    label: 'Project',
    width: '240px',
    sortable: true,
    sortType: 'string',
    textMode: 'expandable',
    cellMaxWidth: '220px',
    previewCharThreshold: 34,
  },
  {
    key: 'inquirySource',
    label: 'Inquiry Source',
    width: '170px',
    sortable: true,
    sortType: 'string',
  },
  {
    key: 'value',
    label: 'Value (RM)',
    width: '130px',
    sortable: true,
    sortType: 'number',
    align: 'center',
    shrinkToFit: true,
    getExportValue: (project) => project.valueDisplay,
  },
  {
    key: 'update',
    label: 'Latest Update',
    width: '220px',
    sortable: true,
    sortType: 'date',
    textMode: 'expandable',
    cellMaxWidth: '220px',
    previewCharThreshold: 34,
    getExportValue: (project) => project.updateFullText,
  },
  {
    key: 'owner',
    label: 'Project Leader',
    width: '150px',
    sortable: true,
    sortType: 'string',
    shrinkToFit: true,
  },
  { key: 'vendor', label: 'Vendor', width: '220px', sortable: true, sortType: 'string' },
  {
    key: 'vendorContactName',
    label: 'Vendor Contact',
    width: '170px',
    sortable: true,
    sortType: 'string',
  },
  {
    key: 'vendorMobile',
    label: 'Vendor Mobile',
    width: '150px',
    sortable: true,
    sortType: 'string',
  },
  { key: 'vendorEmail', label: 'Vendor Email', width: '220px', sortable: true, sortType: 'string' },
  {
    key: 'award',
    label: 'Award',
    width: '120px',
    sortable: true,
    sortType: 'date',
    align: 'center',
    shrinkToFit: true,
    getExportValue: (project) => project.awardDisplay,
  },
  {
    key: 'status',
    label: 'Status',
    width: '120px',
    sortable: true,
    sortType: 'string',
    align: 'center',
    shrinkToFit: true,
  },
  {
    key: 'closed',
    label: 'Closed',
    width: '120px',
    sortable: true,
    sortType: 'date',
    align: 'center',
    shrinkToFit: true,
    getExportValue: (project) => project.closedDisplay,
  },
]
